
using System.Collections.Generic;


namespace pokemon_board_generator
{
    public static class GoldSilver
    {
        public static SquarePool genIIslim = new SquarePool()
        {
            options = new List<Square>{
            new Square("Chickorita", ObjectiveType.Chickorita),
            new Square("Bayleef", ObjectiveType.Chickorita),
            new Square("Meganium", ObjectiveType.Chickorita),
            new Square("Cyndaquil", ObjectiveType.Cyndaquil),
            new Square("Quilava", ObjectiveType.Cyndaquil),
            new Square("Typhlosion", ObjectiveType.Cyndaquil),
            new Square("Totodile", ObjectiveType.Totodile),
            new Square("Croconaw", ObjectiveType.Totodile),
            new Square("Feraligatr", ObjectiveType.Totodile),
            new Square("Sentret", ObjectiveType.Sentret),
            new Square("Furret", ObjectiveType.Sentret),
            new Square("Hoothoot", ObjectiveType.Hoothoot),
            new Square("Noctowl", ObjectiveType.Hoothoot),
            new Square("Ledyba", ObjectiveType.Ledyba),
            new Square("Ledian", ObjectiveType.Ledyba),
            new Square("Spinarak", ObjectiveType.Spinarak),
            new Square("Ariados", ObjectiveType.Spinarak),
            new Square("Crobat", ObjectiveType.Zubat),
            new Square("Chinchou", ObjectiveType.Chinchou),
            new Square("Lanturn", ObjectiveType.Chinchou),
            new Square("Igglybuff", ObjectiveType.Jigglypuff),
            new Square("Togepi", ObjectiveType.Togepi),
            new Square("Togetic", ObjectiveType.Togepi),
            new Square("Natu", ObjectiveType.Natu),
            new Square("Xatu", ObjectiveType.Natu),
            new Square("Mareep", ObjectiveType.Mareep),
            new Square("Flaaffy", ObjectiveType.Mareep),
            new Square("Ampharos", ObjectiveType.Mareep),
            new Square("Bellossom", ObjectiveType.Oddish),
            new Square("Marill", ObjectiveType.Marill),
            new Square("Azumarill", ObjectiveType.Marill),
            new Square("Sudowoodo", ObjectiveType.Single),
            new Square("Hoppip", ObjectiveType.Hoppip),
            new Square("Skiploom", ObjectiveType.Hoppip),
            new Square("Jumpluff", ObjectiveType.Hoppip),
            new Square("Aipom", ObjectiveType.Single),
            new Square("Sunkern", ObjectiveType.Sunkern),
            new Square("Sunflora", ObjectiveType.Sunkern), // need to win bug catching contest for sun stone
            new Square("Yanma", ObjectiveType.Single), // 1% or swarm
            new Square("Wooper", ObjectiveType.Wooper),
            new Square("Quagsire", ObjectiveType.Wooper),
            new Square("Espeon", ObjectiveType.Eevee),
            new Square("Umbreon", ObjectiveType.Eevee),
            new Square("Unown", ObjectiveType.Single),
            new Square("Wobbuffet", ObjectiveType.Single),
            new Square("Girafarig", ObjectiveType.Single),
            new Square("Pineco", ObjectiveType.Pineco),
            new Square("Forretress", ObjectiveType.Pineco),
            new Square("Dunsparce", ObjectiveType.Single), // 1%
            new Square("Gligar", ObjectiveType.Single),
            new Square("Snubbull", ObjectiveType.Snubbull), // 1% or swarm
            new Square("Granbull", ObjectiveType.Snubbull),
            new Square("Qwilfish", ObjectiveType.Single),
            new Square("Shuckle", ObjectiveType.Single),
            new Square("Heracross", ObjectiveType.Single),
            new Square("Teddiursa", ObjectiveType.Teddiursa),
            new Square("Ursaring", ObjectiveType.Teddiursa),
            new Square("Swinub", ObjectiveType.Swinub),
            new Square("Piloswine", ObjectiveType.Swinub),
            new Square("Corsola", ObjectiveType.Single),
            new Square("Remoraid", ObjectiveType.Remoraid),
            new Square("Octillery", ObjectiveType.Remoraid),
            new Square("Delibird", ObjectiveType.Single),
            new Square("Mantine", ObjectiveType.Single),
            new Square("Skarmory", ObjectiveType.Single),
            new Square("Phanpy", ObjectiveType.Phanpy),
            new Square("Donphan", ObjectiveType.Phanpy),
            new Square("Stantler", ObjectiveType.Single),
            new Square("Smeargle", ObjectiveType.Single),
            new Square("Tyrogue", ObjectiveType.Tyrogue),
            new Square("Hitmontop", ObjectiveType.Tyrogue),
            new Square("Smoochum", ObjectiveType.Jynx), // breed
            new Square("Magby", ObjectiveType.Magmar),
            new Square("Miltank", ObjectiveType.Single),
            new Square("Raikou", ObjectiveType.Legendary),
            new Square("Entei", ObjectiveType.Legendary),
            new Square("Suicune", ObjectiveType.Legendary),
            new Square("Lugia", ObjectiveType.Legendary),
            new Square("Ho-Oh", ObjectiveType.Legendary),
			
			// Gen I Pokemon Section
            // Only Pokemon found in Johto
            new Square("Caterpie", ObjectiveType.Caterpie),
            new Square("Metapod", ObjectiveType.Caterpie),
            new Square("Butterfree", ObjectiveType.Caterpie),
            new Square("Weedle", ObjectiveType.Weedle),
            new Square("Kakuna", ObjectiveType.Weedle),
            new Square("Beedrill", ObjectiveType.Weedle),
            new Square("Pidgey", ObjectiveType.Pidgey),
            new Square("Pidgeotto", ObjectiveType.Pidgey),
            new Square("Pidgeot", ObjectiveType.Pidgey),
            new Square("Rattata", ObjectiveType.Rattata),
            new Square("Raticate", ObjectiveType.Rattata),
            new Square("Spearow", ObjectiveType.Spearow),
            new Square("Fearow", ObjectiveType.Spearow),
            new Square("Ekans", ObjectiveType.Ekans),
            new Square("Arbok", ObjectiveType.Ekans),
            new Square("Sandshrew", ObjectiveType.Sandshrew),
            new Square("Sandslash", ObjectiveType.Sandshrew),
            new Square("Nidoran ♀", ObjectiveType.Nidoran_F),
            new Square("Nidorina", ObjectiveType.Nidoran_F),
            new Square("Nidoqueen", ObjectiveType.Nidoran_F), // pain in the ass
            new Square("Nidoran ♂", ObjectiveType.Nidoran_M),
            new Square("Nidorino", ObjectiveType.Nidoran_M),
            new Square("Nidoking", ObjectiveType.Nidoran_M), // pain
            new Square("Vulpix", ObjectiveType.Vulpix),
            new Square("Ninetales", ObjectiveType.Vulpix),
            new Square("Jigglypuff", ObjectiveType.Jigglypuff),
            new Square("Wigglytuff", ObjectiveType.Jigglypuff), // pain
            new Square("Zubat", ObjectiveType.Zubat),
            new Square("Golbat", ObjectiveType.Zubat),
            new Square("Oddish", ObjectiveType.Oddish), // extremely time-locked to Ilex Forest
            new Square("Gloom", ObjectiveType.Oddish),
            new Square("Vileplume", ObjectiveType.Oddish),
            new Square("Paras", ObjectiveType.Paras), // day-locked
            new Square("Parasect", ObjectiveType.Paras), // day-locked
            new Square("Venonat", ObjectiveType.Venonat),
            new Square("Venomoth", ObjectiveType.Venonat),
            new Square("Meowth", ObjectiveType.Meowth),
            new Square("Persian", ObjectiveType.Meowth),
            new Square("Psyduck", ObjectiveType.Psyduck), // Ilex Forest
            new Square("Golduck", ObjectiveType.Psyduck),
            new Square("Mankey", ObjectiveType.Mankey),
            new Square("Primeape", ObjectiveType.Mankey),
            new Square("Growlithe", ObjectiveType.Growlithe),
            new Square("Arcanine", ObjectiveType.Growlithe),
            new Square("Poliwag", ObjectiveType.Poliwag),
            new Square("Poliwhirl", ObjectiveType.Poliwag),
            new Square("Abra", ObjectiveType.Abra),
            new Square("Kadabra", ObjectiveType.Abra),
            new Square("Machop", ObjectiveType.Machop),
            new Square("Machoke", ObjectiveType.Machop),
            new Square("Bellsprout", ObjectiveType.Bellsprout),
            new Square("Weepinbell", ObjectiveType.Bellsprout),
            new Square("Tentacool", ObjectiveType.Tentacool),
            new Square("Tentacruel", ObjectiveType.Tentacool),
            new Square("Geodude", ObjectiveType.Geodude),
            new Square("Graveler", ObjectiveType.Geodude),
            new Square("Slowpoke", ObjectiveType.Slowpoke),
            new Square("Slowbro", ObjectiveType.Slowpoke),
            new Square("Magnemite", ObjectiveType.Magnemite),
            new Square("Magneton", ObjectiveType.Magnemite),
            new Square("Farfetch'd", ObjectiveType.Single), // time-locked
            new Square("Seel", ObjectiveType.Seel),
            new Square("Dewgong", ObjectiveType.Seel),
            new Square("Shellder", ObjectiveType.Shellder),
            new Square("Gastly", ObjectiveType.Gastly), // time-locked
            new Square("Haunter", ObjectiveType.Gastly),
            new Square("Onix", ObjectiveType.Onix),
            new Square("Drowzee", ObjectiveType.Drowzee),
            new Square("Hypno", ObjectiveType.Drowzee),
            new Square("Krabby", ObjectiveType.Krabby),
            new Square("Kingler", ObjectiveType.Krabby),
            new Square("Voltorb", ObjectiveType.Voltorb),
            new Square("Electrode", ObjectiveType.Voltorb),
            new Square("Exeggcute", ObjectiveType.Exeggcute),
            new Square("Hitmonlee", ObjectiveType.Tyrogue), // oh god evolving tyrogue
            new Square("Hitmonchan", ObjectiveType.Tyrogue), // oh god evolving tyrogue
            new Square("Lickitung", ObjectiveType.Single),
            new Square("Koffing", ObjectiveType.Koffing),
            new Square("Weezing", ObjectiveType.Koffing),
            new Square("Tangela", ObjectiveType.Single),
            new Square("Horsea", ObjectiveType.Horsea),
            new Square("Seadra", ObjectiveType.Horsea),
            new Square("Goldeen", ObjectiveType.Goldeen),
            new Square("Seaking", ObjectiveType.Goldeen),
            new Square("Staryu", ObjectiveType.Staryu),
            new Square("Jynx", ObjectiveType.Jynx),
            new Square("Magmar", ObjectiveType.Magmar),
            new Square("Tauros", ObjectiveType.Single),
            new Square("Magikarp", ObjectiveType.Magikarp),
            new Square("Gyarados", ObjectiveType.Magikarp),
            new Square("Ditto", ObjectiveType.Single),
            new Square("Eevee", ObjectiveType.Eevee),
            new Square("Dratini", ObjectiveType.Dratini),
            new Square("Dragonair", ObjectiveType.Dratini),
            new Square("Dragonite", ObjectiveType.Dratini),

            // Readded for Bug catching contest
            new Square("Scyther", ObjectiveType.Scyther),
            new Square("Pinsir", ObjectiveType.Single)
            }
        };
    }
}
