using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace pokemon_board_generator
{
    class RSE
    {
        public static SquarePool genIIIrse = new SquarePool()
        {
            options = new List<Square>
            {
            new Square("Sceptile", ObjectiveType.Treecko),
            new Square("Blaziken", ObjectiveType.Torchic),
            new Square("Swampert", ObjectiveType.Mudkip),
            new Square("Poochyena", ObjectiveType.Poochyena),
            new Square("Mightyena", ObjectiveType.Poochyena),
            new Square("Zigzagoon", ObjectiveType.Zigzagoon),
            new Square("Linoone", ObjectiveType.Zigzagoon),
            new Square("Wurmple", ObjectiveType.Wurmple),
            new Square("Silcoon", ObjectiveType.Wurmple),
            new Square("Beautifly", ObjectiveType.Wurmple),
            new Square("Cascoon", ObjectiveType.Wurmple),
            new Square("Dustox", ObjectiveType.Wurmple),
            new Square("Lotad", ObjectiveType.Lotad),
            new Square("Lombre", ObjectiveType.Lotad),
            new Square("Ludicolo", ObjectiveType.Lotad),
            new Square("Seedot", ObjectiveType.Seedot),
            new Square("Nuzleaf", ObjectiveType.Seedot),
            new Square("Shiftry", ObjectiveType.Seedot),
            new Square("Nincada", ObjectiveType.Nincada),
            new Square("Ninjask", ObjectiveType.Nincada),
            new Square("Shedinja", ObjectiveType.Nincada),
            new Square("Taillow", ObjectiveType.Taillow),
            new Square("Swellow", ObjectiveType.Taillow),
            new Square("Shroomish", ObjectiveType.Shroomish),
            new Square("Breloom", ObjectiveType.Shroomish),
            new Square("Spinda", ObjectiveType.Single),
            new Square("Wingull", ObjectiveType.Wingull),
            new Square("Pelipper", ObjectiveType.Wingull),
            new Square("Surskit", ObjectiveType.Surskit),
            new Square("Masquerain", ObjectiveType.Surskit),
            new Square("Wailmer", ObjectiveType.Wailmer),
            new Square("Wailord", ObjectiveType.Wailmer),
            new Square("Skitty", ObjectiveType.Skitty),
            new Square("Delcatty", ObjectiveType.Skitty),
            new Square("Kecleon", ObjectiveType.Single),
            new Square("Baltoy", ObjectiveType.Baltoy),
            new Square("Claydol", ObjectiveType.Baltoy),
            new Square("Nosepass", ObjectiveType.Single),
            new Square("Torkoal", ObjectiveType.Single),
            new Square("Sableye", ObjectiveType.Single),
            new Square("Barboach", ObjectiveType.Barboach),
            new Square("Whiscash", ObjectiveType.Barboach),
            new Square("Luvdisc", ObjectiveType.Single),
            new Square("Corphish", ObjectiveType.Corphish),
            new Square("Crawdaunt", ObjectiveType.Corphish),
            new Square("Feebas", ObjectiveType.Feebas),
            new Square("Milotic", ObjectiveType.Feebas),
            new Square("Carvanha", ObjectiveType.Carvanha),
            new Square("Sharpedo", ObjectiveType.Carvanha),
            new Square("Trapinch", ObjectiveType.Trapinch),
            new Square("Vibrava", ObjectiveType.Trapinch),
            new Square("Flygon", ObjectiveType.Trapinch),
            new Square("Makuhita", ObjectiveType.Makuhita),
            new Square("Hariyama", ObjectiveType.Makuhita),
            new Square("Electrike", ObjectiveType.Electrike),
            new Square("Manectric", ObjectiveType.Electrike),
            new Square("Numel", ObjectiveType.Numel),
            new Square("Camerupt", ObjectiveType.Numel),
            new Square("Spheal", ObjectiveType.Spheal),
            new Square("Sealeo", ObjectiveType.Spheal),
            new Square("Walrein", ObjectiveType.Spheal),
            new Square("Cacnea", ObjectiveType.Cacnea),
            new Square("Cacturne", ObjectiveType.Cacnea),
            new Square("Snorunt", ObjectiveType.Snorunt),
            new Square("Glalie", ObjectiveType.Snorunt),
            new Square("Lunatone", ObjectiveType.Single),
            new Square("Solrock", ObjectiveType.Single),
            new Square("Azurill", ObjectiveType.Marill), // remember to add Marill family
            new Square("Spoink", ObjectiveType.Spoink),
            new Square("Grumpig", ObjectiveType.Spoink),
            new Square("Plusle", ObjectiveType.Single),
            new Square("Minun", ObjectiveType.Single),
            new Square("Mawile", ObjectiveType.Single),
            new Square("Meditite", ObjectiveType.Meditite),
            new Square("Medicham", ObjectiveType.Meditite),
            new Square("Swablu", ObjectiveType.Swablu),
            new Square("Altaria", ObjectiveType.Swablu),
            new Square("Wynaut", ObjectiveType.Wobbuffet), // add Wobbuffet
            new Square("Duskull", ObjectiveType.Duskull),
            new Square("Dusclops", ObjectiveType.Duskull),
            new Square("Roselia", ObjectiveType.Single),
            new Square("Slakoth", ObjectiveType.Slakoth),
            new Square("Vigoroth", ObjectiveType.Slakoth),
            new Square("Slaking", ObjectiveType.Slakoth),
            new Square("Gulpin", ObjectiveType.Gulpin),
            new Square("Swalot", ObjectiveType.Gulpin),
            new Square("Tropius", ObjectiveType.Single),
            new Square("Whismur", ObjectiveType.Whismur),
            new Square("Loudred", ObjectiveType.Whismur),
            new Square("Exploud", ObjectiveType.Whismur),
            new Square("Clamperl", ObjectiveType.Clamperl),
            new Square("Huntail", ObjectiveType.Clamperl),
            new Square("Gorebyss", ObjectiveType.Clamperl),
            new Square("Absol", ObjectiveType.Single),
            new Square("Shuppet", ObjectiveType.Shuppet),
            new Square("Banette", ObjectiveType.Shuppet),
            new Square("Seviper", ObjectiveType.Single),
            new Square("Zangoose", ObjectiveType.Single),
            new Square("Relicanth", ObjectiveType.Single),
            new Square("Aron", ObjectiveType.Aron),
            new Square("Lairon", ObjectiveType.Aron),
            new Square("Aggron", ObjectiveType.Aron),
            new Square("Castform", ObjectiveType.Single),
            new Square("Volbeat", ObjectiveType.Single),
            new Square("Illumise", ObjectiveType.Single),
            new Square("Lileep", ObjectiveType.Lileep),
            new Square("Cradily", ObjectiveType.Lileep),
            new Square("Anorith", ObjectiveType.Anorith),
            new Square("Armaldo", ObjectiveType.Anorith),
            new Square("Ralts", ObjectiveType.Ralts),
            new Square("Kirlia", ObjectiveType.Ralts),
            new Square("Gardevoir", ObjectiveType.Ralts),
            new Square("Bagon", ObjectiveType.Bagon),
            new Square("Shelgon", ObjectiveType.Bagon),
            new Square("Salamence", ObjectiveType.Bagon),
            new Square("Beldum", ObjectiveType.Beldum),
            new Square("Metang", ObjectiveType.Beldum),
            new Square("Metagross", ObjectiveType.Beldum),
            new Square("Regirock", ObjectiveType.Legendary),
            new Square("Regice", ObjectiveType.Legendary),
            new Square("Registeel", ObjectiveType.Legendary),
            new Square("Kyogre", ObjectiveType.Legendary),
            new Square("Groudon", ObjectiveType.Legendary),
            new Square("Rayquaza", ObjectiveType.Legendary),
            new Square("Latias", ObjectiveType.Legendary),
            new Square("Latios", ObjectiveType.Legendary),
            new Square("Chimecho", ObjectiveType.Legendary),

            // Baby evolutions
            new Square("Wobbuffet", ObjectiveType.Wobbuffet),
            new Square("Marill", ObjectiveType.Marill),
            new Square("Azumarill", ObjectiveType.Marill),
            }
        };
    }
}
